### ISSUE TITLE
Unavailable and broken links

### ISSUE THREAD

**Issue by woctezuma** [mehdidc/feed_forward_vqgan_clip#15]
When I run the notebook, some links seem unavailable.
I don't know why this happens, because it seems that I can manually download the files in my web browser.

![Unavailable links](https://i.imgur.com/EB9jEdY.png)

Moreover, the links in the README are broken.

![Broken links](https://i.imgur.com/9AuJApE.png)

**Comment by mehdidc** [comment]
Hi @woctezuma, thanks for raising this issue, could you please try again the notebook, it should work now.
I will also change the links in the README.

EDIT:  it is weird though that you could manually download them fine in your browser, so this could be another problem. I tried to use the notebook by logging using another gmail account (rather than the one the files belong to), and it did work, not sure what is happening.

**Comment by afiaka87** [comment]
@mehdidc This happened with the original CUB dataset for the dalle-pytorch colab. It was on lucidrains gdrive. I think Google makes them more-restrictive if it gets flagged or something.

**Comment by mehdidc** [comment]
Ah I see, thanks, so perhaps it's better to switch to e.g dropbox

**Comment by woctezuma** [comment]
I don't know if it could help, but I have seen some projects share model checkpoints in the "release" section of the Github project.

For instance: https://github.com/neuralchen/SimSwap/releases
which can be accessed by clicking here:
![Access to releases](https://i.imgur.com/UyAXXqb.png)

**Comment by mehdidc** [comment]
Ah cool thanks @woctezuma , looks like a good solution (there is no total size limit according to the github doc), in fact now I recall  @afiaka87 used it for the blog captions model actually.

**Comment by mehdidc** [comment]
Ok I updated the links using a github release, please try again, thanks for the tip. It's nice, the only issue is that it does not work for files > 2GB.

**Comment by woctezuma** [comment]
It works! Thank you!
